# -*- coding: utf-8 -*-
"""CGS410

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lsWmSmOePkFFdzh_sw4TMZj45NwNwd-u
"""

!pip install conllu pandas scipy matplotlib seaborn tqdm

import os
import conllu
import pandas as pd
import numpy as np
from collections import defaultdict
from scipy import stats
import matplotlib.pyplot as plt
from tqdm import tqdm
import requests

treebanks = {
    "English":"https://raw.githubusercontent.com/UniversalDependencies/UD_English-EWT/master/en_ewt-ud-train.conllu",
    "Hindi":"https://raw.githubusercontent.com/UniversalDependencies/UD_Hindi-HDTB/master/hi_hdtb-ud-train.conllu",
    "Spanish":"https://raw.githubusercontent.com/UniversalDependencies/UD_Spanish-AnCora/master/es_ancora-ud-train.conllu",
    "French":"https://raw.githubusercontent.com/UniversalDependencies/UD_French-GSD/master/fr_gsd-ud-train.conllu",
    "German":"https://raw.githubusercontent.com/UniversalDependencies/UD_German-GSD/master/de_gsd-ud-train.conllu",
    "Italian":"https://raw.githubusercontent.com/UniversalDependencies/UD_Italian-ISDT/master/it_isdt-ud-train.conllu",

}

os.makedirs("treebanks", exist_ok=True)

for lang, url in treebanks.items():
    filename = f"treebanks/{lang}.conllu"

    if not os.path.exists(filename):
        r = requests.get(url)
        with open(filename, "wb") as f:
            f.write(r.content)

print("Downloaded all treebanks")

def subtree_size(token_id, children_dict):
    return 1 + sum(
        subtree_size(c, children_dict)
        for c in children_dict.get(token_id, [])
    )


def analyze_treebank(filepath):

    records = []

    with open(filepath, encoding="utf-8") as f:
        sentences = conllu.parse(f.read())

    for sent in tqdm(sentences):

        tokens = {
            t["id"]: t
            for t in sent
            if isinstance(t["id"], int)
        }

        children = defaultdict(list)

        for t in tokens.values():
            if t["head"] and t["head"] in tokens:
                children[t["head"]].append(t["id"])

        for tok in tokens.values():

            h = tok["head"]
            d = tok["id"]

            if not h or h not in tokens:
                continue

            lo = min(h, d)
            hi = max(h, d)

            for mid in range(lo + 1, hi):

                if mid not in tokens:
                    continue

                w = tokens[mid]

                if w["upos"] == "PUNCT":
                    continue

                records.append({
                    "upos": w["upos"],
                    "arity": len(children[mid]),
                    "size": subtree_size(mid, children),
                    "is_intervener": True
                })

        for tok in tokens.values():

            if tok["upos"] == "PUNCT":
                continue

            records.append({
                "upos": tok["upos"],
                "arity": len(children[tok["id"]]),
                "size": subtree_size(tok["id"], children),
                "is_intervener": False
            })

    return pd.DataFrame(records)

dfs = []

for lang in treebanks:

    print(f"\nProcessing {lang}")

    df_lang = analyze_treebank(
        f"treebanks/{lang}.conllu"
    )

    df_lang["language"] = lang

    dfs.append(df_lang)

all_df = pd.concat(dfs, ignore_index=True)

print("Total Records:", len(all_df))

intervener_df = all_df[
    all_df["is_intervener"]
]

pos_intervener = (
    intervener_df["upos"]
    .value_counts(normalize=True)
)

pos_all = (
    all_df["upos"]
    .value_counts(normalize=True)
)

er = (
    pos_intervener / pos_all
).sort_values(ascending=False)

er_df = pd.DataFrame({
    "ER": er
})

display(er_df)

plt.figure(figsize=(8,5))

er.sort_values().plot(
    kind="barh"
)

plt.axvline(
    x=1,
    linestyle="--"
)

plt.xlabel("Enrichment Ratio")
plt.title("UPOS Enrichment Ratios")
plt.show()

interveners = all_df[
    all_df["is_intervener"]
]["arity"]

all_tokens = all_df[
    ~all_df["is_intervener"]
]["arity"]

t,p = stats.ttest_ind(
    interveners,
    all_tokens,
    alternative="less"
)

cohen_d = (
    all_tokens.mean()
    - interveners.mean()
)/all_tokens.std()

print("Mean Arity (Interveners):",
      interveners.mean())

print("Mean Arity (All Tokens):",
      all_tokens.mean())

print("t =",t)
print("p =",p)
print("Cohen d =",cohen_d)

interveners = all_df[
    all_df["is_intervener"]
]["size"]

all_tokens = all_df[
    ~all_df["is_intervener"]
]["size"]

t,p = stats.ttest_ind(
    interveners,
    all_tokens,
    alternative="less"
)

cohen_d = (
    all_tokens.mean()
    - interveners.mean()
)/all_tokens.std()

print("Mean Size (Interveners):",
      interveners.mean())

print("Mean Size (All Tokens):",
      all_tokens.mean())

print("t =",t)
print("p =",p)
print("Cohen d =",cohen_d)

arity_counts = (
    intervener_df["arity"]
    .clip(upper=2)
    .value_counts(normalize=True)
    .sort_index()
)

arity_counts.plot(
    kind="bar"
)

plt.xticks(
    [0,1,2],
    ["0","1","2+"]
)

plt.ylabel("Proportion")
plt.title("Intervener Arity Distribution")
plt.show()